__title__ = "Quart-Login"
__description__ = "User session management for Quart"
__url__ = "https://github.com/luckydonald/quart-login"
__version_info__ = ("0", "7", "0", "pre1")
__version__ = ".".join(__version_info__)
__author__ = "Luckydonald"
__author_email__ = "quart-login+code@luckydonald.de"
__maintainer__ = "Luckydonald"
__license__ = "MIT"
__copyright__ = "(c) 2023 by Luckydonald"
